[package]
edition = "2021"
name = "sql-query-connector"
version = "0.1.0"

[features]
vendored-openssl = ["quaint/vendored-openssl"]
mysql = ["quaint/mysql", "user-facing-errors/mysql"]
sqlite = ["quaint/sqlite", "user-facing-errors/sqlite"]
mssql = ["quaint/mssql", "user-facing-errors/mssql"]
postgresql = ["quaint/postgresql", "user-facing-errors/postgresql"]

[dependencies]
anyhow = "1.0"
async-trait = "0.1"
bigdecimal = "0.3"
futures = "0.3"
itertools = "0.10"
once_cell = "1.3"
rand = "0.7"
serde_json = { version = "1.0", features = ["float_roundtrip"] }
thiserror = "1.0"
tokio.workspace = true
tracing = "0.1"
tracing-futures = "0.2"
uuid.workspace = true
opentelemetry = { version = "0.17", features = ["tokio"] }
tracing-opentelemetry = "0.17.3"
quaint = { workspace = true, features = ["pooled", "json", "uuid", "chrono", "bigdecimal", "fmt-sql"] }

[dependencies.connector-interface]
package = "query-connector"
path = "../query-connector"

[dependencies.prisma-models]
path = "../../prisma-models"

[dependencies.prisma-value]
path = "../../../libs/prisma-value"

[dependencies.chrono]
features = ["serde"]
version = "0.4"

[dependencies.psl]
workspace = true
features = ["default_generators"]

[dependencies.serde]
features = ["derive"]
version = "1.0"

[dependencies.cuid]
version = "1.2"

[dependencies.user-facing-errors]
path = "../../../libs/user-facing-errors"
features = ["quaint"]
