[package]
name = "qe-setup"
version = "0.1.0"
edition = "2021"

[dependencies]
datamodel = { path = "../../libs/datamodel/core" }
mongodb-client = { path = "../../libs/mongodb-client" }
migration-core = { path = "../core" }

connection-string = "*"
enumflags2 = "*"
mongodb = "2.1.0"
tempfile = "3.3.0"
url = "2"

[dependencies.quaint]
git = "https://github.com/prisma/quaint"
rev = "fb4fe90682b4fecb485fd0d6975dd15a3bc9616b"
features = [
    "sqlite",
    "postgresql",
    "mysql",
    "mssql",
]
